### ISSUE TITLE
Sindragosa

### ISSUE THREAD

**Issue by Xertium** [Xertium/azerothcore-wotlk#11]
#### Sindragosa [36853]

- [x] `HealthModifier` `11,156,000` [`800`] (10 normal) -> `7,809,200` [`560`] (5 normal)
- [x] `DamageModifier` `81.6` (10 normal) -> `35` (5 normal)

#### Before pull

- [x] [Sindragosa's fury](http://wotlk.evowow.com/?spell=70598) — Deals 100000 Frost damage, split between all enemies struck. This spell is highly susceptible to Frost resistance.
  - [x] Reduce to `30,000` from `100,000`

#### Phase One

- [x] [Cleave](http://wotlk.evowow.com/?spell=19983) — Inflicts normal damage plus 50 to an enemy and its nearest allies, affecting up to 10 targets.
- [x] [Frost Aura](http://wotlk.evowow.com/?spell=70084) — Deals 3000 Frost damage to all nearby enemies every 3 sec. Instant. Deals 4500 on Heroic
  - [x] Damage reduced to `1999` from `2999`
- [x] [Frost Breath](http://wotlk.evowow.com/?spell=69649) — Inflicts 27,750 to 32,250 Frost damage to enemies in a 60-yard cone in front of the caster. In addition, the targets' attack speed is decreased by 50% and movement decreased by 15% for 1.50 min. 1.5-sec cast. 37,000 to 43,000 on Heroic
  - [x] Duration reduced to `9s` from `90s`
  - [x] Damage reduced to `17749` from `27749`
- [x] [Icy Grip](http://wotlk.evowow.com/?spell=70117) — Extend tendrils of frigid wind to pull all nearby enemies to the caster. After she uses this, she will follow it up with a Blistering Cold. (6 sec cooldown)
  - [x] [Blistering Cold](http://wotlk.evowow.com/?spell=70123)  — Deals 30,000 Frost damage to enemies within 25 yards. 5 sec cast. 45,000 damage on Heroic
- [x] [Chilled to the Bone](http://wotlk.evowow.com/?spell=70106) — Deals 1000 Frost damage per 2 sec. for each application.
- [x] [Permeating Chill](http://wotlk.evowow.com/?spell=70109) — Causes those who attack Sindragosa with physical attacks to be chilled to the bone, dealing 1000 Frost damage per 2 sec for each application.
- [x] [Tail Smash](http://wotlk.evowow.com/?spell=71077) — Inflicts 11250 to 18750 damage on enemies within 20 yards of the tail's impact point, knocking them back. 1 sec cast
- [x] [Unchained Magic](http://wotlk.evowow.com/?spell=69762) — Inflicts an arcane malediction on the target, causing any spells cast to result in a backlash of Arcane power after 5 sec. Multiple spellcasts by the afflicted target will intensify the backlash. Instant cast.
  - [x] [Instability](http://wotlk.evowow.com/?spell=69766) — Using magic while afflicted with Unchained Magic will build up unstable energy, dealing 2,000 Arcane damage to the caster per spell cast, 5 seconds after spellcasting ends. Instant cast. Stacks 99 times.

#### Phase Two (Air Phase)

Although Sindragosa takes to the air on a recurrent timer, her abilities are distinctively different from phase 1 and therefore is considered its own phase.

- [x] [Frost Beacon](http://wotlk.evowow.com/?spell=70126) — Marks a target for imprisonment in an Ice Tomb. Instant, 7 sec duration. Targets 2 at a time. (10 cooldown)
  - [x] Targets reduced to `1` from `2`.
  - [x] Can't target healer
  - [x] Asphyxiation damage need to be reduced to `2%` from `8%`
  - [x] [Ice Tomb](http://wotlk.evowow.com/?spell=69712) — Conjures spheres of icy energy to entomb enemies in blocks of ice.
  - [x] [Asphyxiation](http://wotlk.evowow.com/?spell=71665) — Suffocation due to lack of air. Deals 8% of total health in damage each second. Occurs if a player encased in an Ice Tomb is not released within 20 seconds
- [x] [Frost Bomb](http://wotlk.evowow.com/?spell=69845) — Deals 23,563 to 26,437 Frost damage to all nearby targets. You need to hide behind Ice Tombs to avoid this damage. Sindragosa will target locations in the room while flying and cast it there. After she uses this 4 times she lands. On Heroic, deals 188,500 to 211,500 and will one-shot any player not in or completely behind an Ice Tomb.

#### Phase Three

All Phase One abilities, plus:

- [x] [Mystic Buffet](http://wotlk.evowow.com/?spell=70128) — Buffets all nearby foes with Arcane energy, increasing all magic damage taken by 10% per application. New stack applied every 4 seconds, stacks 99 times, drops off after 8 seconds if not reapplied, such as when behind an Ice Tomb.
  - [x] Reduced to `5%` per stack from `10%`
