### ISSUE TITLE
The Lich King

### ISSUE THREAD

**Issue by Xertium** [Xertium/azerothcore-wotlk#12]
#### The Lich King [36597]

- [x] `HealthModifier` `17,431,250` [`1250`] (10 normal) -> `11,330,312` [`812.5`] (5 normal)
- [x] `DamageModifier` `139` (10 normal) -> `35` (5 normal)

#### Shambling Horror [36597]

- [x] `unit_class` `1` (10 normal) -> `2`  (5 normal)
- [x] `ManaModifier` `0` (10 normal) -> `150` (5 normal)

#### Val'kyr Shadowguard [36609]

- [x] `HealthModifier` `450,000` [`35.7143`] (10 normal) -> `201,600` [`16`] (5 normal)

#### Vile Spirit [37799]

- [x] `HealthModifier` `65,999` [`5.23809`] (10 normal) -> `6,300` [`0.5`] (5 normal)

#### Raging Spirit

- [x] `HealthModifier` `752,583` [`53.968`] (10 normal) -> `404,405` [`29`] (5 normal)
- [x] `DamageModifier` `66.4` (10 normal) -> `22` (5 normal)

#### Phase 1

- [x] [Summon Drudge Ghouls](http://wotlk.evowow.com/?spell=70358) — Summons 3 Drudge Ghouls over 3 seconds. No abilities outside of basic melee
- [x] [Summon Shambling Horror](http://wotlk.evowow.com/?spell=70372) — Summons a Shambling Horror. Stunnable.
  - [x] ~~[Enrage](http://wotlk.evowow.com/?spell=72143) — Increases Physical damage by 200% 1.25 sec cast (7 sec cooldown)~~
  - [x] ~~[Shockwave](http://wotlk.evowow.com/?spell=72149) — Sends a wave of force in front of the caster, causing 150% weapon damage in a 20 yard cone. 1.25 sec cast. (3 sec cooldown)~~
  - [x] [Shadow bolt volley](http://wotlk.evowow.com/?spell=40428) — Hurls missiles of dark magic, inflicting 1275 to 1725 Shadow damage to nearby enemies.
  - [x] The horror always stands in front of the tank. 
- [x] [Necrotic Plague](http://wotlk.evowow.com/?spell=70337) — Infects the target with a deadly plague, causing 50,000 Shadow damage every 5 seconds for 15 seconds. If the target dies while afflicted, or the effect expires after its 15 sec duration, this effect will gain an additional stack and jump to a nearby unit. The 15 sec timer is refreshed after each jump. If this effect is dispelled, it will lose a stack and jump to a nearby unit in a 10 yard distance, if there is no target the plague will be removed completely. Whenever this effect jumps, the Lich King's power will increase. Instant. Disease. 100,000/5 on 25-player.
  - [x] [Plague Siphon](http://wotlk.evowow.com/?spell=74074) — Increases physical damage dealt by 2%. Stack increases each time Necrotic Plague jumps. 30 sec duration. Stacks to 500
- [x] [Infest](http://wotlk.evowow.com/?spell=70541) — Deals 6,598 to 7,402 Shadow damage to all enemy players within 50,000 yards. In addition, the targets will take increasing Shadow damage per second. This effect is removed when the target has more than 90% health. 2 sec cast. 9,425 to 10,575 on 25-player
  - [x] Damage reduced to `3597` from `6597`
  - [x] And only even ticks increase the damage caused by infest.
- [ ] _[Summon Shadow Trap](http://wotlk.evowow.com/?spell=73539) — Summons a Shadow Trap with a ~5 yard radius under a targeted player after a short delay. Any player who steps inside the Shadow Trap will cause it to explode, dealing 23563 to 26437 shadow damage to all players withing 10 yards and knocking them off of the Frozen Throne. 0.5 sec cast. Heroic mode only_

#### Phase 1.5 and 2.5

- [x] [Remorseless Winter](http://wotlk.evowow.com/?spell=68981) — Creates a massive winter storm, dealing 7069 to 7931 Frost damage per second to all surrounding enemies within 45 yards. 2.5 sec cast. 9425-10575/sec on 25-player
- [x] [Pain and Suffering](http://wotlk.evowow.com/?spell=72133)  — Deals 2828 to 3172 Shadow damage in a cone effect in front of the caster. In addition, the targets will take 500 Shadow damage per second for 3 sec. 0.5 sec cast. Stacks to 5. 4713-5287+800/sec for 3 sec on 25-player
- [x] [Summon Ice Sphere](http://wotlk.evowow.com/?spell=69104) — Summons 1 Ice Sphere with around 6000 health. Moves towards a random raid memeber When it reaches its target...
  - [x] [Ice Burst](http://wotlk.evowow.com/?spell=69108) — Deals 9425 to 10575 Frost damage to all enemies within 10 yards, knocking them back. Instant. Knockback typically leads to getting blown off the edge of the platform. 14138 to 15862 on 25-player
- [x] [Raging Spirit](http://wotlk.evowow.com/?spell=69200)  — Rips out a piece of the target's spirit, causing it to attack them. Instant. Summons a Raging Spirit with...
  - [x] [Soul Shriek](http://wotlk.evowow.com/?spell=69242) — Deals 18850 to 21150 Shadow damage to all enemies in a 15 yard cone in front of the caster, silencing them for 5 sec. 0.5 sec cast. 28275-31725 on 25-player
  - [x] Damage reduced to `8850` from `18850`
- [x] [Quake](http://wotlk.evowow.com/?spell=72262) — Sends out underground shockwaves, causing the edge of the platform to crumble. 1.5 sec cast. Cast at the end of the phase.

#### Phase 2

The Lich King retains Infest.

- [x] [Soul Reaper](http://wotlk.evowow.com/?spell=69409) — Strikes the target for 50% weapon damage and afflicts the target with Soul Reaper. This effect deals 50,000 Shadow damage after 5 sec and increases the caster's haste by 100% for 5 sec. Instant. Used on the tank. 60,000 on 25-player and 10-player heroic, 70,000 on 25-player heroic.
  - [x] Damage reduced to `40,000` from `50,000`
- [x] [Defile](http://wotlk.evowow.com/?spell=72762) — Defiles the area under a random target. Any enemies within this area will be dealt shadow damage. Any damage that Defile deals will increase its size of the area. Lasts 30s. 2 sec cast. Starts at 3000/sec on 10-player, 5000/sec on 25-player. (3 sec cooldown)
- [x] [Summon Val'kyr](http://wotlk.evowow.com/?spell=69037) — Summons a Val'kyr Shadowguard. Instant. Attempts to pick up a player and drop them off the edge of Icecrown Citadel. (3 sec cooldown)
  - [x] Can't target tank or healer.
  - [ ] _[Life Siphon](http://wotlk.evowow.com/?spell=73488) — Deals 1850 to 2150 Shadow damage to an enemy target, healing the caster for 10 times the damage dealt. 2 sec cast. Heroic mode only. Cast at 50% health after dropping the player_

#### Phase 3

The Lich King retains Soul Reaper and Defile.

- [x] [Harvest Soul](http://wotlk.evowow.com/?spell=68980) — Attempts to harvest the target's soul, dealing 7500 Shadow damage per second for 6 sec. If the target is still alive after the channel is completed, the target's soul will be transfered into Frostmourne to be devoured. Channeled. 15,000/sec on 25-player
  - [x] Can't target tank or healer.
  - [x] Damage reduced to `4500` from `5000`
- [ ] _[Harvest Souls](http://wotlk.evowow.com/?spell=72679) — Attempts to harvest the soul of all nearby enemies, dealing 2000 Shadow damage per second for until cancelled. If a target is still alive after the channel is completed, that target's soul will be transfered into Frostmourne to be devoured. Heroic mode only._
- [x] [Harvested Soul](http://wotlk.evowow.com/?spell=73654) — Applied when a raid member dies inside Frostmourne, increases damage dealt by 200% and size by 50%. Normal mode only, 15 sec duration.
- [ ] _[Harvested Soul](http://wotlk.evowow.com/?spell=72679) — Applied when a raid member dies inside Frostmourne, increases damage dealt by 500% and size by 50%. Heroic mode only, can stack, 15 sec duration._
- [x] [Vile Spirits](http://wotlk.evowow.com/?spell=70498) — Creates 10 Vile Spirits which will attack enemies after 30 seconds.
  - [x] [Spirit Burst](http://wotlk.evowow.com/?spell=70503) — Sacrifices the caster, dealing 18850 to 21150 Shadow damage to all enemies within 5 yards. Instant. 28275-31725 on 25-player
  - [x] Damage reduced to `13,850` from `18,850`

#### Frostmourne

- [x] [Harvest Soul](http://wotlk.evowow.com/?spell=68980) — Slowly consumes the soul of the target, dealing 2000 Shadow damage per second. Debuff on players inside Frostmourne, does NOT deal damage on normal.

#### Spirit Warden

- [x] [Soul Rip](http://wotlk.evowow.com/?spell=69397) — Deals increasing Shadow damage to your target every second for 8 sec. Channeled on Terenas. Magic debuff — can be dispelled
- [x] [Dark Hunger](http://wotlk.evowow.com/?spell=69383) — Heals the caster for half of any damage dealt. Aura on the Spirit Warden
- [x] [Destroy Soul](http://wotlk.evowow.com/?spell=74086) — Instantly kills the raid member inside Frostmourne if Terenas dies. Causes Arthas to gain the powerful Harvested Soul debuff. Instant cast.

#### Terenas Menethil

- [x] [Light's Favor](http://wotlk.evowow.com/?spell=69382) — Heals the caster for 5000 every second and increases damage dealt proportional to health. Aura on Terenas
- [x] [Restore Soul](http://wotlk.evowow.com/?spell=72595) — Returns the target's soul to their body, bringing them back to life. Cast on the raid member inside Frostmourne after the Spirit Warden's death. 2 sec cast.
- [ ] _[Restore Soul (Heroic)](http://wotlk.evowow.com/?spell=73650) — Terenas starts casting this when the raid enters Frostmourne in Phase 3 of the Heroic encounter. The raid is ported out when it completes. 40 sec cast._

#### Phase 4

- [x] [Fury of Frostmourne](http://wotlk.evowow.com/?spell=72350) — Deals 1,000,000 Shadow damage to all enemies and rendering them unable to release spirit or resurrect. 2.6 sec cast. Cast at the beginning of phase 4
- [x] [Raise Dead](http://wotlk.evowow.com/?spell=71769) — Raises the dead back to life to serve as undead slaves to the Lich King. Channeled. Cast after gloating over the corpses of the raid.

#### Terenas Menethil

Resurrects all nearby fallen allies.
