### ISSUE TITLE
Lady Deathwhisper

### ISSUE THREAD

**Issue by Xertium** [Xertium/azerothcore-wotlk#2]
#### Lady Deathwhisper [36855]
- [x] `HealthModifier` `3,346,800` [`300`] (10 normal) -> `2,231,000` [`200`] (5 normal)
- [x] `ManaModifier` `3,264,800` [`350`] (10 normal) -> `2,332,000` [`250`] (5 normal)
- [x] `DamageModifier` `69.3` (10 normal) -> `40` (5 normal)

#### Cult Fanatic [37890]
- [x] `HealthModifier` `134,810` [`10`] (10 normal) -> `n` [`n`] (5 normal)
- [x] `DamageModifier` `25.4` (10 normal) -> `n` (5 normal)

#### Reanimated Fanatic [38009]
- [x] `HealthModifier` `134,810` [`10`] (10 normal) -> `n` [`n`] (5 normal)
- [x] `DamageModifier` `7.5` (10 normal) -> `n` (5 normal)

#### Deformed Fanatic [38135]
- [x] `HealthModifier` `134,810` [`10`] (10 normal) -> `n` [`n`] (5 normal)
- [x] `DamageModifier` `76.2` (10 normal) -> `n` (5 normal)

#### Cult Adherent [37949]
- [x] `HealthModifier` `107,840` [`10`] (10 normal) -> `n` [`n`] (5 normal)
- [x] `DamageModifier` `10.1` (10 normal) -> `n` (5 normal)

#### Reanimated Adherent [38010]
- [x] `HealthModifier` `134,810` [`10`] (10 normal) -> `n` [`n`] (5 normal)
- [x] `DamageModifier` `7.5` (10 normal) -> `n` (5 normal)

#### Empowered Adherent [38136]
- [x] `HealthModifier` `134,810` [`10`] (10 normal) -> `n` [`n`] (5 normal)
- [x] `DamageModifier` `7.5` (10 normal) -> `n` (5 normal)

#### Vengeful Shade [38222]
- [x] `speed_walk` `n` (10 normal) -> `n` (5 normal)
- [x] `speed_run` `n` (10 normal) -> `n` (5 normal)

#### Both Phases
- [x] [Death and Decay](https://wotlk.evowow.com/?spell=71001) ([Heroic mode](https://wotlk.evowow.com/?spell=72109)) — 4500 Shadow damage inflicted every 1 sec to all targets in the affected area for 10 seconds. Instant. 8 yd radius. 6000 on Heroic
  - [x] Need to reduce the damage MASSIVELY because in 10-man version the DnD only affects 2-4 raid member but with 5-man group will be problematic. 
  - [x] Damage reduced from `4500` to `3000`

#### Phase one only
- [x] [Animate Dead]—Reanimates a Cult Adherent or a Cult Fanatic.
- [x] [Dark Empowerment](https://wotlk.evowow.com/?spell=70901) 200 yd range—Empowers the recipient's spells, causing them to deal area damage and making them uninterruptable. 2 sec cast.
- [x] [Dark Transformation](https://wotlk.evowow.com/?spell=70900) 200 yd range—Transforms one random Cult Fanatic into an undead behemoth, increasing damage dealt by 100%. 2.5 second cast.
- [x] [Mana Barrier](https://wotlk.evowow.com/?spell=70842) the caster in a powerful barrier that continually replenishes any lost health, at the expense of the caster's mana.
- [x] [Shadow Bolt]—Inflicts 9,188 to 11,812 Shadow damage to an enemy. 100 yard range. 2 seconds cast.
  - [x] Need to be reduced a bit.
  - [x] Damaged reduced from `7438` to `3500`

#### Phase two only
- [x] [Frostbolt] 40 yd range—Inflicts 37,000 Frost damage to an enemy and reduces its movement speed by 50% for 4 seconds. 2 sec cast. Interruptable but unresistable on heroic difficulty. 44,850 to 47,150 on Heroic.
  - [x] Need to be reduced.
  - [x] Damage reduced from `40949` to `30949`
- [x] [Frostbolt Volley]—Inflicts 10800 to 13200 Frost damage to nearby enemies, reducing their movement speed for 4 sec. Instant.
  - [x] Need to be reduced.
  - [x] Base damage reduced from `8549` to `6549`
- [ ] [Summon Vengeful Shade]—Calls an unattackable Vengeful Shade that chases a player for a short time, casting Vengeful Blast upon catching them.
  - [ ] Need to be decrease Shade's movement speed.
- [x] [Touch of Insignificance](https://wotlk.evowow.com/?spell=71204) 50,000 yd range—Reduces the target's threat generation by 20%. Instant. Stacks to five. Lasts 30 seconds.
  - [x] Decreased the threat generation from `20%` to `10%`

#### Cult Adherent / Empowered Adherent / Reanimated Adherent
- [x] [Adherent's Determination](https://wotlk.evowow.com/?spell=71234) impervious to magical damage. 99% reduction. Reanimated Adherent only
- [x] ~~[Curse of Torpor](https://wotlk.evowow.com/?spell=71237) 100 yd range—Afflicts an enemy target with a curse that increases ability cooldowns by 15 seconds. 1 sec cast. Curse~~
- [x] [Deathchill Bolt](https://wotlk.evowow.com/?spell=70594) ([Heroic mode](https://wotlk.evowow.com/?spell=72488)) 45 yd range—Deals 6938 to 8062 Shadowfrost damage to an enemy target. 2 sec cast. 8788-10212 on Heroic
  - [x] Damage reduced from `6937` to `3500`
- [x] [Frost Fever] 50,000 yd range—A disease dealing Frost damage every 3 seconds and reducing the target's melee and ranged attack speed by 14% for 15 seconds. Instant
  - [x] Duration reduced from `15s` to `9s`
- [x] [Shroud of the Occult](https://wotlk.evowow.com/?spell=70768) the caster in a powerful barrier that reflects all harmful magic, prevents cast interruption, and absorbs up to 50,000 damage before breaking. Instant. Used randomly.
  - [x] Decreased armor from `50000` to `20000`
- [x] [Deathchill Blast](https://wotlk.evowow.com/?spell=70906) ([Heroic mode](https://wotlk.evowow.com/?spell=72486)) 45 yd range—Deals 9250 to 10750 Shadowfrost damage to all enemies within 10 yards of the target. 2 sec cast. Only cast while empowered. 11563-13437 on Heroic
  - [x] Need to be reduced.
  - [x] Damaged reduced from `9250` to `7000`
- [x] [Dark Martyrdom]—The caster surrenders to dark energies, exploding to deal 12000 Shadowstorm damage to all enemies within 15 yards, and leaving only skeletal remains behind, thus becoming reanimated after a few seconds of death. 4 sec cast. Cast randomly.
  - [ ] __Need to be reduced.__

#### Cult Fanatic / Deformed Fanatic / Reanimated Fanatic
- [x] [Fanatic's Determination](https://wotlk.evowow.com/?spell=71235) impervious to physical damage. 99% reduction. Reanimated Fanatic only
- [x] ~~[Necrotic Strike](https://wotlk.evowow.com/?spell=70659) ([Heroic mode](https://wotlk.evowow.com/?spell=72491)) Melee range—Strikes an enemy with a cursed blade, dealing 70% of weapon damage to the target and inflicting a lasting malady that negates the next 9000 healing received. Instant. 20 sec duration. 14000 healing on Heroic~~
- [x] [Vampiric Might](https://wotlk.evowow.com/?spell=70674) the caster with dark might, increasing all damage dealt by 25% and heals the caster for 300% of his damage dealt. Instant. Magic. 15 sec duration. Used randomly.
  - [ ] __It's a good question. I think this ability is way too powerfull.__
- [x] [Shadow Cleave](https://wotlk.evowow.com/?spell=70670) ([Heroic mode](https://wotlk.evowow.com/?spell=72493)) Melee range—Inflicts 14250 to 15750 Shadow damage to enemies in front of the attacker. Next melee. 8 yard radius. 19000-21000 on Heroic (6 sec cooldown)
  - [x] Need to be reduced.
  - [x] Damage reduced from `14250` to `7000`
- [x] [Dark Martyrdom]—The caster surrenders to dark energies, exploding to deal 12000 Shadowstorm damage to all enemies within 15 yards, and leaving only skeletal remains behind, thus becoming reanimated after a few seconds of death. 4 sec cast. Cast randomly.
  - [ ] __Need to be reduced.__

#### Vengeful Shade
- [x] [Vengeful Blast](https://wotlk.evowow.com/?spell=72011) Melee range—Inflicts 17370 to 18630 Shadowfrost damage to all enemies within 15 yards of the target.
  
#### Add summoning
- [x] Need to reduce number of adds summoned by boss.
